config/routes.rb
Rails.application.routes.draw do
  root to: "events#index"

  devise_for :users
  get '/users', to: 'users#index'
  get '/users/:id', to: 'users#show', as: 'user'

  resources :events
  resources :invitations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :event_date, presence: true

  scope :published, -> { where(published: true) }
  scope :planned, -> { where(published: false) }
  scope :can_join, -> { where(open_join: true) }
  scope :no_join, -> { where(open_join: false) }
  scope :past, -> { where('event_date < ?', Date.today) }
  scope :upcoming, -> { where('event_date >= ?', Date.today) }

  has_one :host, foreign_key: 'id', class_name: 'User'
  has_many :invitations, dependent: :destroy
  has_many :attendees, through: :invitations
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show index]

  # GET /events or /events.json
  def index
    @public_events = Event.includes(:host).published.upcoming
    @past_events = Event.includes(:host).past
    @pending_events = current_user.hosted_events.planned if user_signed_in?
  end

  # GET /events/1 or /events/1.json
  def show
    @current_event = Event.find(params[:id])
    @current_guests = @current_event.attendees.all
    @current_user_invite = Invitation.where(attendee_id: current_user.id, event_id: params[:id]).take if user_signed_in?

    respond_to do |format|
      format.html
      format.json { render json: Event.find(params[:id]) }
    end
  end

  # GET /events/new
  def new
    @event = current_user.hosted_events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.hosted_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to :root, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event = current_user.hosted_events.find(params[:id])

    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :event_date, :open_join, :max_guests, :published)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <article>
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </article>
  <% end %>

  <div class="container">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="container">
    <%= form.label :event_date %>
    <div class="grid">
      <%= form.datetime_select :event_date %>
    </div>
  </div>

  <div class="grid">
    <div class="container">
      <%= form.label :open_join %>
      <%= form.check_box :open_join %>
    </div>

    <div class="container">
      <%= form.label :published %>
      <%= form.check_box :published %>
    </div>
  </div>

  <div class="container">
    <%= form.label :max_guests %>
    <%= form.number_field :max_guests %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% unless @pending_events.nil? || @pending_events.empty? %>
  <section>
    <h4>Draft Events</h4>
    <ul>
    <% @pending_events.each do |event| %>
      <li>
        <p>
          <%= link_to event.name, event %>
          <% if user_signed_in? && event.creator_id == current_user.id %>
            (<%= link_to 'Edit', edit_event_path(event) %> | 
            <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>)
          <% end %>
        </p>
      </li>
    <% end %>
    </ul>
  </section>
<% end %>

<div class="grid">
  <section>
    <h1>Published Events</h1>
    <% @public_events.each do |event| %>
      <article>
        <header>
          <hgroup>
            <h4><%= link_to event.name, event %></h4>
            <h5>Hosted by: <%= event.host.name %> at <%= event.event_date %></h5>
          </hgroup>
        </header>
        <p>
          <small>Maximum guests: <%= event.max_guests %></small>
        </p>
        <% if user_signed_in? && event.creator_id == current_user.id %>
          <footer>
            <nav>
              <ul>
                <li><%= link_to 'Edit', edit_event_path(event) %></li>
                <li><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              </ul>
            </nav>
          </footer>
        <% end %>
      </article>
    <% end %>
    </section>

  <section>
    <h1>Past Events</h1>
    <% @past_events.each do |event| %>
      <article>
        <header>
          <hgroup>
            <h4><%= link_to event.name, event %></h4>
            <h5>Hosted by: <%= event.host.name %> at <%= event.event_date %></h5>
          </hgroup>
        </header>
        <p>
          <small>Maximum guests: <%= event.max_guests %></small>
        </p>
        <% if user_signed_in? && event.creator_id == current_user.id %>
          <footer>
            <nav>
              <ul>
                <li><%= link_to 'Edit', edit_event_path(event) %></li>
                <li><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              </ul>
            </nav>
          </footer>
        <% end %>
      </article>
    <% end %>
  </section>

  

</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h2><%= @event.name %></h2>
<p>
  <strong>Event date:</strong> <%= @event.event_date %><br>
  <strong>Capacity Limit:</strong> <%= @event.max_guests %><br>
  <% unless @current_guests.nil? %>
    <strong>Current guests: </strong>
    <ul>
    <% @current_guests.each do |guest| %>
      <li><%= guest.name %></li>
    <% end %>
    </ul><br>
  <% end %>
  <% if @event.open_join %>
    <% if @event.attendees.include?(current_user) %>
      You've already joined this event! <%= link_to 'Remove me from the guest list.', invitation_path(@current_user_invite), method: :delete, data: { confirm: 'Really?' } %>
    <% else %>
      <%= link_to 'You can still join this event.', new_invitation_path(:event_id => @event.id) %>
    <% end %>
  <% else %>
      This event is not open to join at the moment.
  <% end %>
</p>

<% if user_signed_in? %>
  <% if @event.creator_id == current_user.id %>
    <%= link_to 'Edit Event', edit_event_path(@event) %>
    <%= link_to 'Remove Event', event_path(@event), method: :delete %>
  <% end %>
<% end %>
<%= link_to 'Back', root_path %>