config/routes.rb
Rails.application.routes.draw do
  root to: "events#index"

  devise_for :users
  get '/users', to: 'users#index'
  get '/users/:id', to: 'users#show', as: 'user'

  resources :events
  resources :invitations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :event
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_invitation, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /invitations or /invitations.json
  def index
    @invitations = Invitation.all
  end

  # GET /invitations/1 or /invitations/1.json
  def show
  end

  # GET /invitations/new
  def new
    event = Event.find(params[:event_id])
    redirect_to :root, alert: 'Event is currently not accepting more attendees.' unless event.open_join
    redirect_to :root, alert: 'Event is in the past.' unless event.event_date >= DateTime.now

    @invitation = current_user.invitations.build
  end

  # GET /invitations/1/edit
  def edit
  end

  # POST /invitations or /invitations.json
  def create
    event = Event.find(params[:invitation][:event_id])
    redirect_to :root, alert: 'Event is currently not accepting more attendees.' unless event.open_join || event.to_come

    @invitation = current_user.invitations.build(invitation_params)

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to :root, notice: 'You joined the event!' }
        format.json { render :show, status: :created, location: @invitation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invitations/1 or /invitations/1.json
  def update
    respond_to do |format|
      if @invitation.update(invitation_params)
        format.html { redirect_to invitation_url(@invitation), notice: "Invitation was successfully updated." }
        format.json { render :show, status: :ok, location: @invitation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1 or /invitations/1.json
  def destroy
    @invitation.destroy

    respond_to do |format|
      format.html { redirect_to :root, notice: 'You are no longer an attendee of that event.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invitation
      @invitation = Invitation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invitation_params
      params.require(:invitation).permit(:event_id, :attendee_id)
    end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<h2><%= event.name %></h2>
<p><%= event.event_date %></p>

<%= form_with(model: invitation) do |form| %>
  <% if invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
        <% invitation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :event_id, value: params[:event_id] %>
  <%= form.hidden_field :attendee_id %>

  <div class="actions">
    <%= form.submit value: "Join!" %>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing Invitation</h1>

<%= render 'form', invitation: @invitation %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', root_path %>

app/views/invitations/index.html.erb
<h1>Invitations</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Attendee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invitations.each do |invitation| %>
      <tr>
        <td><%= invitation.event_id %></td>
        <td><%= invitation.attendee_id %></td>
        <td><%= link_to 'Show', invitation %></td>
        <td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
        <td><%= link_to 'Destroy', invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invitation', new_invitation_path %>
<%= link_to 'Back', root_path %>

app/views/invitations/new.html.erb
<h1>Join Event</h1>

<%= render 'form', invitation: @invitation, event: Event.find(params[:event_id]) %>

<%= link_to 'Back', root_path %>

app/views/invitations/show.html.erb
<p>
  <strong>Event:</strong>
  <%= @invitation.event_id %>
</p>

<p>
  <strong>Attendee:</strong>
  <%= @invitation.attendee_id %>
</p>

<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', root_path %>