config/routes.rb
Rails.application.routes.draw do
  root to: "events#index"

  devise_for :users
  get '/users', to: 'users#index'
  get '/users/:id', to: 'users#show', as: 'user'

  resources :events
  resources :invitations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> -->
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav>
        <ul>
          <li><strong>Hostware</strong></li>
        </ul>
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to current_user.name, edit_user_registration_path(current_user) %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'New Event', new_event_path %></li>
            <% end %>
            <li><%= link_to 'My Events', user_path(current_user) %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign Up or Log On", new_user_session_path, method: :get %></li>
          <% end %>
        </ul>
      </nav>
    </div>     
    <% unless flash[:notice].nil? %>
      <div class="container"><ins><%= notice %></ins></div>
    <% end %>
    <% unless flash[:alert].nil? %>
      <div class="container"><mark><%= alert %></mark></div>
    <% end %>
    <main class="container">
      <%= yield %>
    </main>
    <footer class="container">
      Thanks for checking this out!
    </footer>
  </body>
</html>